spring.application.name=system
server.port=8081
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:sqlserver://;serverName=10.123.12.2;databaseName=Lippo_HRIS_System;encrypt=true;trustServerCertificate=true
spring.datasource.username=Proint.Admin
spring.datasource.password=#L!pp0K@r4w@c!

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT settings
jwt.secret=F4P8Q89rf7n4vk2986Y1Eiq+EVJQOLQu8W3a8uLZGhZMdxzrqpDi1T0+D9IVdzCckkKhb7j1Mpgru3S7CoWD+Q==
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=hrislippo2025@gmail.com
spring.mail.password=lsmrjyborjuaxmea

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true

spring.security.oauth2.client.registration.google.client-id=565692718989-50qlnn2s31i2isia2tptfn3rggn9qb34.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.refresh-token=1//0gQTNNZKTNQbnCgYIARAAGBASNwF-L9IrJumJ7STc0EcXHStDEqC3zIyyCM5Batbgd99FkNg3asXiGaxWILHBHb6HdJ5xQkE1P5s
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/drive
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent

google.client-id=565692718989-50qlnn2s31i2isia2tptfn3rggn9qb34.apps.googleusercontent.com
google.client-secret=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
google.refresh-token=1//0gRjUfYlV7mlECgYIARAAGBASNwF-L9IrIO2lcBM2UUuV72O0arHyGUCr9ThHe3sdKwNOhDoccFoG7xHjLIVoMzWurjtlxp9qCB0
google.folder-cv=1yaRuc-YMy17CTrn9fZwiY9j7zOH0zkLh
google.folder-result=1juZcOfbYJ3n8_W6yWn5DIvN2SOacGCfg